### ISSUE TITLE
Bad naming

### ISSUE THREAD

**Issue by mileung** [rastapasta/react-native-animated-math#1]
Sinus, Cosinus, Tangens? Shouldn't they be Sin, Cos, and Tangent?

**Comment by euharrison** [comment]
Maybe use javascript `Math` reference https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math

**Comment by rastapasta** [comment]
Hey @MiLeung & @euharrison - thanks for checking in and sorry for havin' kept this issue open for so long :)

The freshly released v0.2.0 addresses this and offers (inclusive backwards compatibility) following methods:

* sin
* cos
* tan
* pow
* subtract
